# Generated by Django 4.2.15 on 2025-05-27 07:21

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("user_auth", "0002_alter_admin_log_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomLogEntry",
            fields=[],
            options={
                "verbose_name": "Log Entry",
                "verbose_name_plural": "Log Entries",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin.logentry",),
            managers=[
                ("objects", django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
